checkup/urls.py
from django.urls import path

from . import views

app_name = 'checkup'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('seo/', views.SeoView.as_view(), name='seo'),
    path('broken_links/', views.IndexView.broken_links, name='broken_links'),
    path('keywords/', views.IndexView.keywords, name='keywords'),
    path('render_template/', views.IndexView.render_template, name='render_template')
]

seo_tool/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include#, path
from django.urls import path

urlpatterns = [
    path('', include('checkup.urls')),
    url(r'^admin/', admin.site.urls),
]

checkup/models.py
import datetime

from django.db import models
from django.utils import timezone

from .validators import validate_url


class Rule(models.Model):
    name = models.CharField(max_length=200, unique=True)
    category = models.CharField(
        choices=(
            ('common', 'Common'),
            ('server', 'Server'),
            ('advanced_seo', 'Advanced SEO'),
        ),
        max_length=200,
    )
    description = models.TextField(max_length=5000, null=True, blank=True)
    priority = models.CharField(
        choices=(
            ('high', 'High'),
            ('medium', 'Medium'),
            ('low', 'Low'),
        ),
        max_length=200,
        default='medium',
    )

    def __str__(self):
        return self.name

class Message(models.Model):
    name = models.ForeignKey(Rule, on_delete=models.CASCADE, related_name='rule_name')
    message = models.TextField(max_length=5000)
    status = models.NullBooleanField()
    def __str__(self):
        return self.message#[:75] + '...' if len(self.message) > 75 else self.message

checkup/forms.py
from django import forms

from .validators import validate_url, url_exists

class SubmitUrlForm(forms.Form):
    url = forms.CharField(max_length=5000, label='Submit URL', validators=[validate_url, url_exists])
    #url = forms.URLField(max_length=200, help_text="input page URL", initial='http://', label='')

checkup/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.http import JsonResponse

import requests
import json

from bs4 import BeautifulSoup
from tkinter import *

from  .forms import SubmitUrlForm
from .models import Rule, Message
from .crawler import Crawler
from .scraper import Scraper

class IndexView(generic.ListView):
    template_name = 'checkup/index.html'
    context_object_name = 'latest_website_list'

    def get(self, request, *args, **kwargs):
        form = SubmitUrlForm()
        context = {
            'title': 'Submit URL',
            'form': form
        }
        return render(request, 'checkup/index.html', context)

    def post(self, request):
        form = SubmitUrlForm(request.POST)
        if(form.is_valid()):
            rules = Rule.objects.all()
            rules_and_messages = Rule.objects.all().prefetch_related('rule_name')
            final = {rule.name: dict(dict({el['status']: el for el in rule.rule_name.filter(name=rule).values()}, **{'priority': rule.priority}), **{'category': rule.category}) for rule in rules_and_messages}#{rule.name: dict({el['status']: el for el in rule.rule_name.filter(name=rule).values()}, **{'priority': rule.priority}) for rule in rules_and_messages}#{rule.name: {el['status']: dict(el, **{'priority': rule.priority}) for el in rule.rule_name.filter(name=rule).values()} for rule in rules_and_messages}
            crawler = Crawler(form.cleaned_data.get('url'), final)
            result = crawler.crawl(1)
            #crawler = Scraper(form.cleaned_data.get('url'))
            #result = crawler.scrap()
            context = {
                'url': form.cleaned_data.get('url'),
                'seo_result': result,
                'descriptions': rules,
                'desc': final
            }
        else:
            form = SubmitUrlForm(request.POST)
            context = {
                'title': 'Submit URL',
                'form': form
            }
            return render(request, 'checkup/index.html', context)
        return render(request, 'checkup/seo_check.html', context)
        #return render(request, 'checkup/scrap.html', context)

    def broken_links(request):
        if request.is_ajax():
            #print(request.GET['url'])
            rules = Rule.objects.all()
            rules_and_messages = Rule.objects.all().prefetch_related('rule_name')
            final = {rule.name: dict(dict({el['status']: el for el in rule.rule_name.filter(name=rule).values()}, **{'priority': rule.priority}), **{'category': rule.category}) for rule in rules_and_messages}
            message = "Yes, AJAX!"
            crawler = Crawler(request.GET['url'], final)
            broken_links = crawler.check_broken_links(True)
            #print(crawler)
            #print(broken_links)
            #print(crawler.modal_data)
            #return render(request, 'checkup/dynamic_result.html', {'content': {'Broken Links': broken_links}, 'modal_data': crawler.modal_data})
            #row = render(request, 'checkup/dynamic_result.html', {'content': {'Broken Links': broken_links}})
            return JsonResponse({'response': broken_links, 'modal_data': crawler.modal_data})
            return render(request, 'checkup/update.html', {'context': 'bandeles'})
        else:
            message = "Not Ajax"

        return HttpResponse(message)

    def render_template(request):
        print(request.GET.keys())
        print(request.GET.values())
        return render(request, 'checkup/dynamic_result.html', {'content': {'Broken Links': request.GET['data']}})

    def keywords(request):
        if request.is_ajax():
            rules = Rule.objects.all()
            rules_and_messages = Rule.objects.all().prefetch_related('rule_name')
            final = {rule.name: dict(dict({el['status']: el for el in rule.rule_name.filter(name=rule).values()}, **{'priority': rule.priority}), **{'category': rule.category}) for rule in rules_and_messages}

            message = "Yes, AJAX!"

            crawler = Crawler(request.GET['url'], final)
            crawler.format_keyword_data(crawler.keyword_results())

            return JsonResponse(crawler.modal_keywords)
            return render(request, 'checkup/update.html', {'context': 'bandeles'})
        else:
            message = "Not Ajax"

        return HttpResponse(message)

class SeoView(generic.ListView):
    template_name = 'checkup/seo_check.html'
    context_object_name = 'context'

    def get(self, request, url="", *args, **kwargs):
        form = SubmitUrlForm(request.POST)
        context = {
            'title': 'Submit URL',
            'form': form
        }
        return render(request, 'checkup/seo_check.html', context)

    def post(self, request):
        self.context = request
        return render(self.request, 'checkup/seo_check.html', self.context)

checkup/templates/checkup/dynamic_result.html
{% load filters %}

{% for key, value in content.items %}
    <tr>
        <th scope="row" class="speed" value="{% if value.passed|yesno:"yeah,no,maybe" == 'yeah' %}true{% elif value.passed|yesno:"yeah,no,maybe" == 'no' %}false{% elif value.passed|yesno:"yeah,no,maybe" == 'maybe' %}null{% endif %}" id="{{ key }}">{{ key }}</th>
        <td>
            {% if value|get_type != 'str' and value|get_type != 'bool' and value|get_type != 'Tag' %}
                {% if value|length == 1 %}
                    {{ value|title }}
                {% elif value|length > 1 %}
                    {% if value|get_type == 'dict' %}
                        {% if 'keyword' in key %}
                            {{ value }}
                        {% endif %}
                        {% if value.passed|yesno:"yeah,no,maybe" == 'yeah' %}
                            <p class="text-success"><i class="material-icons">check</i> {{ value.msg }}{% if value.msg_data %}{{ value.msg_data|safe }}{% endif %}</p>
                        {% elif value.passed|yesno:"yeah,no,maybe" == 'no' %}
                            <p class="text-danger"><i class="material-icons">cancel</i> {{ value.msg }}{% if value.msg_data %}{{ value.msg_data|safe }}{% endif %}</p>
                        {% elif value.passed|yesno:"yeah,no,maybe" == 'maybe' %}
                            <p class="text-dark"><i class="material-icons">error_outline</i> {{ value.msg }}{% if value.msg_data %}{{ value.msg_data|safe }}{% endif %}</p>
                        {% else %}
                            {{ value }}
                        {% endif %}

                        {% if value.html and value.html != '[]' %}
                            <button class="btn btn-danger btn-sm" {% if key == 'Broken Links' %}disabled{% endif %} type="button" id="{{ key }}-btn" onclick="prepare_modal('{{ key }}')">Details!</button>
                        {% endif %}
                    {% else %}
                        {% for item in value %}
                            <p><small>{{ item }}</small></p>
                        {% empty %}
                            hey<br/>
                        {% endfor %}
                    {% endif %}
                {% else %}
                    {{ value }}
                {% endif %}
            {% else %}
                {{ value }}
            {% endif %}
        </td>
    </tr>
{% endfor %}

checkup/templates/checkup/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'checkup/style.css' %}" />

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">SEO Checkup</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/admin">Login</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container text-center" id="urldiv">
    <h1 class="h3 mb-3 font-weight-normal">SEO Tool</h1>
    <form class="form-signin" method="POST" action="{% url 'checkup:index' %}" onchange="checkUrl()" onsubmit="start_loader()">
        {% csrf_token %}

        {{ form.as_p }}
        <div class="checkbox mb-3">
        </div>
        <input type="submit" value="Submit" class="btn btn-lg btn-primary btn-block">

    </form>
    <div class="loader"></div>
</div>

<footer class="text-center" id="footer">
    <p class="mt-5 mb-3 text-muted">© 2018</p>
</footer>

<script>
    var input = document.getElementById('id_url');
    var error_list = document.querySelector('.errorlist');
    input.classList.add("form-control");
    input.placeholder =  placeholder="Submit Url";

    if(error_list) {
        error_list.classList.add("list-group");
        for (var error of error_list.children) {
            error.classList.add("alert");
            error.classList.add('alert-danger');
        }
    }

    function checkUrl() {
        var url = input.value;
        if(!url.startsWith("http://") && !url.startsWith("https://")){
            input.value = 'http://' + url;
        }
    }

    function start_loader() {
        $('form').hide();
        $('.loader').show();
    }
</script>

checkup/templates/checkup/scrap.html
{% load filters %}
{% load static %}

<ul>
{% for key, value in seo_result.items %}
    <li>
        <h3>{{ key }} : {{ value|length }} | {{ value|get_type }} -</h3>
        {% if value|get_type != 'str' and value|get_type != 'bool' and value|get_type != 'Tag' %}
            {% if value|length == 1 %}
                {{ value }}
            {% elif value|length > 1 %}
                {% for item in value %}
                    <p><small>{{ item }}</small></p>
                {% empty %}
                    hey<br/>
                {% endfor %}
            {% else %}
                {{ value }}
            {% endif %}
        {% else %}
            {{ value }}
        {% endif %}
    </li>
{% endfor %}
</ul>

checkup/templates/checkup/update.html
<div>Update view {{ context }}</div>